name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run test
