name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - name: setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.0"
      - run: bun install
      - run: bun run test
