name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
      - run: npm i -g pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test
